# Scikit Learn :

## Support Vector Machine(SVM) Classifer

In [1]:
from sklearn import svm
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
 iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris.target   # in this 0 is setosa, 1 is versicolor, 2 is virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [86]:
X = iris.data[:,2]

In [87]:
y = iris.target

In [88]:
from sklearn.model_selection import train_test_split
import numpy as np

In [89]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 4)

In [90]:
X_train_mod = X_train.reshape(-1,1)

In [91]:
X_test_mod = X_test.reshape(-1,1)

In [92]:
y_train_mod = y_train.reshape(-1,1)

In [93]:
y_test_mod = y_test.reshape(-1,1)

In [94]:
model = svm.SVC(kernel='linear')

In [95]:
model.fit(X_train_mod, np.ravel(y_train_mod))

SVC(kernel='linear')

In [96]:
y_pred_mod = model.predict(X_test_mod)

In [97]:
from sklearn.metrics import accuracy_score

In [99]:
print(accuracy_score(y_test_mod, y_pred_mod, normalize = True))

0.9666666666666667


## Knn / K nearest neighbors

In [102]:
from sklearn.datasets import load_iris
iris = load_iris()

In [103]:
X = iris.data
y = iris.target

In [105]:
X.shape       # rows and columns

(150, 4)

In [106]:
y.shape

(150,)

In [122]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=4)

In [127]:
a = np.array([4,5,6,2])
a.shape

(4,)

In [128]:
knn.predict([a])   # array([2]) 2 is verginica

array([2])

# Logistic Regression

In [129]:
from sklearn.linear_model import LogisticRegression

In [134]:
logreg = LogisticRegression()
logreg.fit(X,y)

C:\Users\Nikhil\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [135]:
logreg.predict([a])

array([2])

# Thank you